# Generated by Django 5.2.5 on 2025-08-26 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relocations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('van', 'Van'), ('truck_small', 'Small Truck'), ('truck_medium', 'Medium Truck'), ('truck_large', 'Large Truck'), ('trailer', 'Trailer'), ('container', 'Container')], max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990)])),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('max_weight_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_volume_cubic_meters', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('mileage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_expiry', models.DateField()),
                ('registration_expiry', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vehicle_id'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('cdl_class', models.CharField(blank=True, help_text='CDL class if applicable', max_length=10)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('on_leave', 'On Leave')], default='available', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_moves', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['driver_id'],
            },
        ),
        migrations.CreateModel(
            name='MovingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_start_date', models.DateTimeField()),
                ('scheduled_end_date', models.DateTimeField()),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_special_equipment', models.BooleanField(default=False)),
                ('special_equipment_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('relocation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='relocations.relocationrequest')),
            ],
            options={
                'ordering': ['-scheduled_start_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('room_from', models.CharField(max_length=100)),
                ('room_to', models.CharField(blank=True, max_length=100)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H in cm', max_length=100)),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_disassembly', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('packed_datetime', models.DateTimeField(blank=True, null=True)),
                ('loaded_datetime', models.DateTimeField(blank=True, null=True)),
                ('delivered_datetime', models.DateTimeField(blank=True, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('damage_reported', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfers', to='logistics.movingassignment')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MovingCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=20, unique=True)),
                ('max_capacity_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('crew_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_crews', to='logistics.driver')),
                ('members', models.ManyToManyField(blank=True, related_name='crew_memberships', to='logistics.driver')),
                ('vehicles', models.ManyToManyField(blank=True, related_name='assigned_crews', to='logistics.vehicle')),
            ],
            options={
                'ordering': ['crew_id'],
            },
        ),
        migrations.AddField(
            model_name='movingassignment',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='logistics.movingcrew'),
        ),
        migrations.CreateModel(
            name='MovingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('fuel', 'Fuel'), ('tolls', 'Tolls'), ('parking', 'Parking'), ('meals', 'Meals'), ('accommodation', 'Accommodation'), ('equipment_rental', 'Equipment Rental'), ('repairs', 'Vehicle Repairs'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=200)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('date_incurred', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='logistics.movingassignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_expenses', to='logistics.driver')),
            ],
            options={
                'ordering': ['-date_incurred'],
            },
        ),
    ]
