# Generated by Django 5.2.5 on 2025-08-26 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=20, unique=True)),
                ('destination_address', models.TextField(blank=True)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('destination_state', models.CharField(blank=True, max_length=100)),
                ('destination_zip', models.CharField(blank=True, max_length=10)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('relocation_type', models.CharField(choices=[('local', 'Local Move'), ('long_distance', 'Long Distance Move'), ('international', 'International Move'), ('corporate', 'Corporate Relocation')], default='local', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('preferred_date', models.DateField()),
                ('alternative_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('requires_packing', models.BooleanField(default=False)),
                ('requires_unpacking', models.BooleanField(default=False)),
                ('requires_storage', models.BooleanField(default=False)),
                ('requires_insurance', models.BooleanField(default=True)),
                ('requires_cleaning', models.BooleanField(default=False)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_relocations', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocation_requests', to='clients.client')),
                ('destination_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relocations_to', to='properties.property')),
                ('origin_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations_from', to='properties.property')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RelocationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('packing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transportation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_services_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_until', models.DateField()),
                ('terms_and_conditions', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
                ('relocation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='relocations.relocationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RelocationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('quote_sent', 'Quote Sent'), ('quote_accepted', 'Quote Accepted'), ('survey_scheduled', 'Survey Scheduled'), ('survey_completed', 'Survey Completed'), ('packing_started', 'Packing Started'), ('packing_completed', 'Packing Completed'), ('loading_started', 'Loading Started'), ('loading_completed', 'Loading Completed'), ('in_transit', 'In Transit'), ('unloading_started', 'Unloading Started'), ('unloading_completed', 'Unloading Completed'), ('unpacking_started', 'Unpacking Started'), ('unpacking_completed', 'Unpacking Completed'), ('relocation_completed', 'Relocation Completed')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('relocation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='relocations.relocationrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_datetime', 'date_created'],
            },
        ),
    ]
